### ISSUE TITLE
Wabe's Roadmap

### ISSUE THREAD

**Issue by coratgerl** [palixir/wabe#16]
# Wabe's Roadmap

## V1.0

Before release the v1 we will need to add some majore features. We also need a stable release using in production without any bug.

- [ ] Fully featured dashboard to visualize and manage all your datas
- [ ] Fully generated REST API
- [ ] Stripe support
- [ ] Mailgun support
- [ ] LLM integration (need to see which we will support in first)
- [ ] PostgreSQL support
- [ ] File adapter for main providers (Google, Amazon)
